config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  root 'static_pages#home'

  get '/contact', to: 'static_pages#contact'

  get '/about',   to: 'static_pages#about'

  devise_for :users, controllers: { registrations: 'users/registrations'}
    
  devise_scope :user do
     get '/sign_up', to: 'devise/registrations#new'
     get '/log_in',  to: 'devise/sessions#new'
     get '/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:create, :show, :index] do
     member do
        get :following, :followers 
     end
     resources :beers, only: [:index] 
  end
  resources :beers 
  resources :relationships, only: [:create, :destroy]
    
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :user
    
  validates :name, presence: true
  validates :user_id, presence: true
  validates :rating, presence: true
  validate :rating_between_zero_and_five 
  validates :brewery, presence: true
  validates :style, presence: true
      
  def rating_between_zero_and_five
    if rating < 0 || rating > 5
       errors.add(:rating, "Keep your rating between 0 and 5!") 
    end
  end
    
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
    
  def index
    @user = User.find_by(id: params[:user_id])
    @beers = current_user.beers
  end
    
  def new
     @beer = Beer.new 
  end

  def create
    @beer = current_user.beers.create(beer_params)
    if @beer.save
      flash[:success] = "Another beer down sir!"
      redirect_to user_path(current_user)
    end
  end

  def show
  end
    
  def edit
    @beer = Beer.find(params[:id]) 
  end
    
  def update
    @beer = Beer.find(params[:id])
    if @beer.update_attributes(beer_params)
      flash[:notice] = "Beer updated!" 
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    beer = Beer.find(params[:id])
    beer.destroy
    respond_to do |format|
       format.js
       format.html { redirect_to request.referrer || root_url }
    end
  end
    
  private
    
  def beer_params
    params.require(:beer).permit(:name, :rating, :style, :brewery, :date, :description, :cellar_date)  
  end
    
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<div class="row">
    <form class="col s12">
      <div class="row">
    <%= form_for(@beer) do |f| %>

    <div class="input-field col s6">
      <%= f.label :Brewery %>
      <%= f.text_field :brewery %>
    </div>

    <div class="input-field col s6">
      <%= f.label :Name %>
      <%= f.text_field :name %>
    </div>

    <div class="input-field col s6">
      <%= f.label :Style %>
      <%= f.text_field :style %>
    </div>

    <div class="input-field col s6">
      <%= f.label :Description %>
      <%= f.text_area :description, id: "textarea1", class: "materialize-textarea" %>
    </div>

    <div class="col s6">
      <%= f.label :Bottle_Date %>
      <%= f.date_field :date, class: "datepicker" %>
    </div>

    <div class="col s6">
      <%= f.label :Cellar_Date %>
      <%= f.date_field :cellar_date %>
    </div>

    <div class="col s6">
      <%= f.label :rating %>
      <%= f.range_field :rating, id: "test5", min: "0.0", max: "5.0" %>
    </div>

      <%= f.submit "Add" %>

    <% end %>
</div>

app/views/beers/_table.html.erb
<table class="table table-bordered" id="beer_table">
    <thead>
      <tr>
      <th>Brewery</th>
      <th>Name</th>
      <th>Style</th>
      <th>Description</th>
      <th>Bottle Date</th>
      <th>Cellar Date</th>
      <th>Rating</th>
        </tr>
    </thead>
      <% @user.beers.each do |beer| %>
      <tbody>
            <tr>
                <td> <%= beer.brewery %> </td>
                <td> <%= beer.name %> </td>
                <td> <%= beer.style %> </td>
                <td> <%= beer.description %></td>
                <% if beer.date %>
                  <td> <%= beer.date.to_s(:custom_datetime) %>
                </td>
                <% else %>
                  <td>No date</td>
                <% end %>
                <% if beer.cellar_date %>
                  <td><%= beer.cellar_date.to_s(:custom_datetime) %></td>
                <% else %>
                  <td>No date</td>
                <% end %>
                <td> <%= beer.rating %></td>
                <% if @user == current_user %>
                  <td> <%= link_to "Edit", edit_beer_path(beer) %> </td>
                  <td> <%= link_to "Delete", beer_path(beer), method: :delete %> </td>
                <% end %>
            </tr>
      <% end %>
    </tbody>
</table>

app/views/beers/create.html.erb
<h1>Beers#create</h1>
<p>Find me in app/views/beers/create.html.erb</p>

app/views/beers/destroy.html.erb
<h1>Beers#destroy</h1>
<p>Find me in app/views/beers/destroy.html.erb</p>

app/views/beers/edit.html.erb
<%= render 'form' %>

app/views/beers/index.html.erb
<h1><%= @user.name %>'s Cellar </h1>

<%= render 'table' %>

app/views/beers/new.html.erb
<%= form_for @beer do |f| %>

<%= f.label :Name %>
<%= f.text_field :name %>

<%= f.label :rating %>
<%= f.text_field :rating %>

<%= f.submit "Add" %>

<% end %>

app/views/beers/show.html.erb
<h1>Beers#show</h1>
<p>Find me in app/views/beers/show.html.erb</p>