config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  root 'static_pages#home'

  get '/contact', to: 'static_pages#contact'

  get '/about',   to: 'static_pages#about'

  devise_for :users, controllers: { registrations: 'users/registrations'}
    
  devise_scope :user do
     get '/sign_up', to: 'devise/registrations#new'
     get '/log_in',  to: 'devise/sessions#new'
     get '/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:create, :show, :index] do
     member do
        get :following, :followers 
     end
     resources :beers, only: [:index] 
  end
  resources :beers 
  resources :relationships, only: [:create, :destroy]
    
end

app/views/layouts/_footer.html.erb
<nav class="nav navbar inverse">
    <ul class="footer_left">
        <li id="logo">
            <%= link_to "Home", root_url %>
        </li>
    </ul>
    <ul class="footer_right">
        <li> <%= link_to "About", about_url %></li>
        <li><%= link_to "Contact", contact_url %></li>
<% if user_signed_in? %>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Log out", sign_out_url %></li>
<% else %>
        <li><%= link_to "Sign up", sign_up_url %></li>
        <li><%= link_to "Log in", log_in_url %></li>
<% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerCellar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <% flash.each do |message_type, message | %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %></div>
        <% end %>
    <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>